const extendedWebpackConfig = require("./webpack/extended-config");

module.exports = {
  devOptions: {
    fallback: "/index.html",
  },
  mount: {
    public: "/",
    src: "/_dist_",
  },
  alias: {
    "@app": "./src",
    "@css": "./src/css",
    "@js": "./src/js",
  },
  // Due to snowpack fuckin' warnings on "modules": false in dev mode...
  install: [
    "regenerator-runtime/runtime",
    "core-js/modules/es.symbol",
    "core-js/modules/es.symbol.description",
    "core-js/modules/es.symbol.iterator",
    "core-js/modules/es.array.for-each",
    "core-js/modules/es.array.from",
    "core-js/modules/es.array.iterator",
    "core-js/modules/es.array.map",
    "core-js/modules/es.array.reverse",
    "core-js/modules/es.array.slice",
    "core-js/modules/es.function.name",
    "core-js/modules/es.map",
    "core-js/modules/es.object.to-string",
    "core-js/modules/es.promise",
    "core-js/modules/es.regexp.to-string",
    "core-js/modules/es.string.iterator",
    "core-js/modules/esnext.map.delete-all",
    "core-js/modules/esnext.map.every",
    "core-js/modules/esnext.map.filter",
    "core-js/modules/esnext.map.find",
    "core-js/modules/esnext.map.find-key",
    "core-js/modules/esnext.map.includes",
    "core-js/modules/esnext.map.key-of",
    "core-js/modules/esnext.map.map-keys",
    "core-js/modules/esnext.map.map-values",
    "core-js/modules/esnext.map.merge",
    "core-js/modules/esnext.map.reduce",
    "core-js/modules/esnext.map.some",
    "core-js/modules/esnext.map.update",
    "core-js/modules/web.dom-collections.for-each",
    "core-js/modules/web.dom-collections.iterator",
    "core-js/modules/es.symbol.description",
    "core-js/modules/es.symbol.iterator",
    "core-js/modules/es.array.concat",
    "core-js/modules/es.array.filter",
    "core-js/modules/es.array.find",
    "core-js/modules/es.array.for-each",
    "core-js/modules/es.array.from",
    "core-js/modules/es.array.index-of",
    "core-js/modules/es.array.iterator",
    "core-js/modules/es.array.last-index-of",
    "core-js/modules/es.array.map",
    "core-js/modules/es.array.reduce",
    "core-js/modules/es.array.slice",
    "core-js/modules/es.function.name",
    "core-js/modules/es.object.entries",
    "core-js/modules/es.object.get-own-property-descriptor",
    "core-js/modules/es.object.get-own-property-descriptors",
    "core-js/modules/es.object.keys",
    "core-js/modules/es.object.to-string",
    "core-js/modules/es.promise",
    "core-js/modules/es.regexp.to-string",
    "core-js/modules/es.string.iterator",
    "core-js/modules/web.dom-collections.for-each",
    "core-js/modules/web.dom-collections.iterator",
    "core-js/modules/es.string.split",
    "core-js/modules/es.string.replace",
    "core-js/modules/es.string.match",
    "core-js/modules/es.regexp.exec",
    "core-js/modules/es.object.is",
    "core-js/modules/es.number.constructor",
    "core-js/modules/es.array.splice",
    "core-js/modules/es.array.join",
    "core-js/modules/es.array.join",
  ],
  plugins: [
    "@snowpack/plugin-babel",
    [
      "@snowpack/plugin-run-script",
      {
        cmd: "postcss --verbose src/css/index.postcss -o src/css/index.css",
        watch: "$1 --watch",
      },
    ],
    [
      "@snowpack/plugin-run-script",
      {
        cmd: "eleventy",
        watch: "$1 --watch",
      },
    ],
    [
      "@snowpack/plugin-webpack",
      {
        outputPattern: {
          assets: "_dist_/img/build/[name].[ext]",
        },
        extendConfig: (config) => {
          config.plugins = [
            ...config.plugins,
            ...extendedWebpackConfig.plugins,
          ];
          return config;
        },
      },
    ],
  ],
};
